### PR TITLE
DLPX-86675 Disk quota exceeded when unpacking an upgrade image

### PR DESCRIPTION
**Pull request by prakashsurya**
It looks like there's a new config directory for the 5.15 kernel, so I think the prior OVERRIDES file is no longer getting applied. This change moves the file to the correct location for the 5.15 kernel. No changes being made to the file contents as part of this change.

### Related Work

* https://github.com/delphix/linux-kernel-azure/pull/28
* https://github.com/delphix/linux-kernel-gcp/pull/28
* https://github.com/delphix/linux-kernel-generic/pull/27
* https://github.com/delphix/linux-kernel-oracle/pull/27

### CODE REVIEW

**Review by sebroy — APPROVED** [review]

**Comment by prakashsurya** [comment]
`git-ab-pre-push` with changes to all kernel (e.g. to check upgrade image size) is [here](http://selfservice.jenkins.delphix.com/job/appliance-build-orchestrator-pre-push/5941/)

**Review by pgandhi-delphix — APPROVED** [review]

**Comment by prakashsurya** [comment]
upgrade image is back down to 4.6G with these changes (applied to all kernels):
```
$ sudo get-property-from-image internal-qa.upgrade.tar VERSION
13.0.0.0-snapshot.20230627015835706+jenkins-selfservice-appliance-build-develop-pre-push-586

$ ls -lh internal-qa.upgrade.tar
-rw-r--r-- 1 delphix staff 4.6G Jun 27 03:48 internal-qa.upgrade.tar
```

**Comment by prakashsurya** [comment]
@sebroy I had to make the following additional changes to get the build to work on all the platforms:
```
--- a/debian.aws-5.15/config/OVERRIDES
+++ b/debian.aws-5.15/config/OVERRIDES
@@ -18,6 +18,7 @@ CONFIG_WIRELESS=n
 # Disable various "drivers" modules which we don't use.
 #
 CONFIG_ACCESSIBILITY=n
+CONFIG_AMD_PMC=n
 CONFIG_ATA=n
 CONFIG_ATM_DRIVERS=n
 CONFIG_AUXDISPLAY=n
@@ -67,7 +68,6 @@ CONFIG_SFI=n
 CONFIG_SIOX=n
 CONFIG_SLIMBUS=n
 CONFIG_SOUNDWIRE=n
-CONFIG_SPI=n
 CONFIG_SPMI=n
 CONFIG_STAGING=n
 CONFIG_THERMAL=n
 ```
 are you OK with this?

**Comment by sebroy** [comment]
@prakashsurya yeah, that seems fine to me. I'm curious to know why the build depends on SPI, but I'm fine with it.

**Comment by prakashsurya** [comment]
```
12:08:11  ERROR: modpost: "__spi_register_driver" [drivers/misc/mei/mei-vsc.ko] undefined!
12:08:11  ERROR: modpost: "spi_sync_locked" [drivers/misc/mei/mei-vsc.ko] undefined!
```
this was the error, and only on some kernels (e.g. generic)..

seems like the `mei-vsc` module is currently built, and it depends on a symbol that was no longer being built due to our `CONFIG_SPI` setting.. I haven't determined why this didn't fail on 5.4.. we might be able to solve this by removing `mei-vsc` as well (in addition to SPI), but I can look into that in a follow up PR, as it wasn't clear if removing `mei-vsc` was OK for us to do.. re-enabling SPI seemed safer to me.

**Pull request merged**
